# Unique key for your project (found in SonarCloud)
sonar.projectKey=a88ae35b6630ebb17c5c3939106a1eb12f9f1b01

# Your SonarCloud organization handle
sonar.organization=moxomega88

# Tell Sonar to only scan the 'src' folder (where your React code lives)
sonar.sources=src

# Tell Sonar where to find your test results (if you run tests)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding of the source code
sonar.sourceEncoding=UTF-8